// 25 items preset pour nouvelle grille bingo.
// Ordre = capture d'écran : ligne par ligne, gauche → droite.
export const BINGO_PRESETS: string[] = [
  'Livre avec de la magie',
  "Livre choisi par l'autre",
  'Lire un livre sans connaître le résumé',
  'Livre avec une couverture jaune',
  'Lire un policier',
  'Lire une romance gay',
  'Livre de Stephen King',
  'Finir une trilogie ou +',
  'Lire un livre en 24h',
  'Livre sur le voyage',
  'Livre en accord avec la période',
  'Livre qui se passe sur une autre planète',
  "Livre dont le perso principal est le vilain",
  "Relire un livre d'enfance",
  'Finir un livre jamais terminé',
  'Livre à plusieurs POV',
  "Livre d'un auteur français",
  'Lire un livre adapté',
  "Livre d'un auteur non anglophone",
  'Livre de référence',
  'Lire un thriller',
  'Livre qui se finit mal',
  'Livre de + de 500 pages',
  'Livre sorti en 2000',
  "Livre qui n'est pas un roman",
];
