import { BINGO_CELLS } from "@/types/bingo";

// Catalogue officiel de défis exposé dans le picker et utilisé comme pool
// pour seeder la grille initiale d'un nouveau bingo (5x5 = 25 items piochés
// au hasard).
export const BINGO_PRESETS: string[] = [
  "Livre avec de la magie",
  "Livre choisi par l'autre",
  "Lire un livre sans connaître le résumé",
  "Livre avec une couverture jaune",
  "Lire un policier",
  "Lire une romance gay",
  "Finir une trilogie ou +",
  "Lire un livre en 24h",
  "Lire un livre d’un auteur que tu n’as jamais lu",
  "Livre sur le voyage",
  "Livre en accord avec la période",
  "Livre qui se passe sur une autre planète",
  "Livre dont le perso principal est le vilain",
  "Relire un livre d'enfance",
  "Finir un livre jamais terminé",
  "Livre à plusieurs POV",
  "Livre d'un auteur français",
  "Lire un livre adapté",
  "Livre d'un auteur non anglophone",
  "Livre de référence",
  "Lire un thriller",
  "Livre qui se finit mal",
  "Livre de + de 500 pages",
  "Livre sorti en 2000",
  "Livre qui n'est pas un roman",
  "Lire une romance",
  "Un livre avec des dragons",
  "Livre dont l’auteur.e a le même prénom que moi",
  "Un livre avec des animaux",
  "Un coup de cœur",
  "Choisis une étagère, compte jusqu’au 15eme livre et lis-le !",
  "Un livre avec une couleur dans le titre",
  "Un livre « Young Adult »",
  "Un livre « Fantasy »",
  "Un livre « S-F »",
  "Un livre angoissant",
  "Un livre emprunté",
  "Une réécriture d’un classique",
  "Un livre avec une romance interdite",
  "Un livre que j’aimerais oublier pour le relire une première fois !",
  "Un livre qui parle de livres",
  "Le plus petit livre de ma PAL",
  "Le plus gros livre de ma PAL",
  "Le dernier livre d’une saga",
  "Un livre acheté pour sa couverture",
  "Un livre avec une couverture que je trouve laide",
  "Un livre avec un saut dans le temps",
  "Un livre avec un perso de plus de 30 ans",
  "Un livre auto-edité",
  "Un livre cosy",
  "Un format poche",
  "Un livre qui traîne dans ma PAL depuis plus d’un an",
  "Un livre qui m’a fait rire !",
  "Un livre qui m’a fait pleurer",
  "Un livre inspiré d’une histoire vraie",
  "Un livre de Noël",
  "Un livre avec un nombre dans le titre",
  "Un best-seller",
  "Lire un préquel",
  "Lire un spin-off",
  "Lire une « Dark Romance »",
  "Un livre avec plusieurs auteurs",
  "Un livre avec un prénom dans le titre",
  "Un ennemies to lovers",
  "Un livre avec un personnage principal solitaire",
  "Un livre acheté d’occasion",
  "Un livre avec des amis d’enfance",
  "Le premier livre d’une saga",
  "Un livre avec une fratrie",
  "Un livre qui me rend nostalgique",
  "Un livre qui devrait être adapté en film/série",
  "Un livre avec un mariage arrangé",
  "Un livre avec un ou des dieux/déesses",
  "Un livre pris au hasard dans ma bibliothèque",
  "Un livre avec un personnage amnésique",
  "Un livre sur plusieurs générations",
  "Un de mes livres préférés",
  "Un livre avec des jeux-vidéo",
  "Un livre sans histoire d’amour",
  "Un livre lu en même temps qu’un.e ami.e",
  "Un livre où le personnage est un artiste",
  "Un livre écrit par un homme",
  "Un livre écrit par une femme",
  "Un livre avec de la royauté",
];

// Pioche aléatoire de BINGO_CELLS labels distincts pour la grille initiale.
// Fisher–Yates partiel : O(n) sans muter BINGO_PRESETS.
export function pickInitialPresetLabels(): string[] {
  const pool = BINGO_PRESETS.slice();
  const n = Math.min(BINGO_CELLS, pool.length);
  for (let i = 0; i < n; i++) {
    const j = i + Math.floor(Math.random() * (pool.length - i));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n);
}
